### PR TITLE
[spryker-internal-jira] FAN-3: creation of products and product attributes

### PR DESCRIPTION
**Pull request by muhammad-kamran-spryker**
https://spryker.atlassian.net/projects/FAN/issues/FAN-3

### CODE REVIEW

**Comment by hhebbo** [comment]
why are we updating the data, shouldn't this come from the product owner side?

**Comment by hhebbo** [comment]
why are we updating the data, shouldn't this come from the product owner side?

**Comment by muhammad-kamran-spryker** [comment]
@hhebbo you are right. However, it was decided after consultation with @christianvonschassen that we setup some sample demo data that roughly reflects the requirements we had at that point in time.

**Comment by hhebbo** [comment]
okay

**Pull request merged**
